name: RDP con tmate (Método Manual y Fiable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: 1. Habilitar RDP, Usuario y Sonido
        run: |
          $Password = "P@ssw0rdFeloxPC2025!"
          net user Runner $Password /add /y
          net localgroup administrators Runner /add
          net localgroup "Remote Desktop Users" Runner /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389
          Set-Service -Name Audiosrv -StartupType Automatic
          Start-Service -Name Audiosrv

      - name: 2. Dar Acceso Manual con tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: 3. Mostrar Instrucciones y Credenciales
        run: |
          Write-Host "======================================================================================"
          Write-Host "                          INSTRUCCIONES PARA ACCESO MANUAL"
          Write-Host "======================================================================================"
          Write-Host ""
          Write-Host "1. Conéctate usando la dirección SSH que aparece en el paso anterior."
          Write-Host ""
          Write-Host "2. Una vez dentro de la terminal, ejecuta este comando para DESCARGAR playit.gg:"
          Write-Host "   curl -L -o playit.exe https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe"
          Write-Host ""
          Write-Host "3. Ahora, ejecuta este comando para INICIAR playit.gg:"
          Write-Host "   ./playit.exe"
          Write-Host ""
          Write-Host "4. Busca la URL de reclamación (https://playit.gg/claim/...) y úsala en tu navegador."
          Write-Host ""
          Write-Host "======================================================================================"
          Write-Host "                             CREDENCIALES DE RDP"
          Write-Host "======================================================================================"
          Write-Host ""
          Write-Host "   Usuario:    Runner"
          Write-Host "   Contraseña: P@ssw0rdFeloxPC2025!"
          Write-Host ""
          Write-Host "======================================================================================"
