name: RDP Optimizado (Estable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: 1. Configuración Avanzada (RDP, Usuario, Sonido y Optimización)
        run: |
          # --- HABILITAR RDP, USUARIO Y SONIDO ---
          $Password = "P@ssw0rdFeloxPC2025!"
          net user Runner $Password /add /y
          net localgroup administrators Runner /add
          net localgroup "Remote Desktop Users" Runner /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389
          Set-Service -Name Audiosrv -StartupType Automatic
          Start-Service -Name Audiosrv
          echo "RDP_USER=Runner" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "RDP_PASSWORD=$Password" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          # --- OPTIMIZACIÓN DE RENDIMIENTO (Forzar CPU) ---
          Write-Host "Optimizando el sistema para forzar el uso de CPU..."
          # 1. Poner Windows en modo "Mejor Rendimiento"
          Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects' -Name 'VisualFxSetting' -Value 2
          # 2. Desactivar aceleración por hardware en Microsoft Edge
          New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft" -Name "Edge" -Force
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Edge" -Name "HardwareAccelerationModeEnabled" -Value 0 -Type DWord -Force
          # 3. Optimizar el servicio RDP para no depender de hardware gráfico
          New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT" -Name "Terminal Services" -Force
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -Name "fEnableHardwareRDP" -Value 0 -Type DWord -Force

      - name: 2. Iniciar Túnel y Mantener Activo (Método Automático Estable)
        run: |
          # (Este paso se queda exactamente igual que antes)
          Invoke-WebRequest -Uri 'https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86__64-signed.exe' -OutFile "playit.exe"
          Start-Process -FilePath ".\playit.exe" -ArgumentList "" -NoNewWindow -RedirectStandardOutput "$env:TEMP\playit.log" -RedirectStandardError "$env:TEMP\playit_error.log"
          Write-Host "Esperando 30 segundos a que playit.gg se conecte..."
          Start-Sleep -Seconds 30
          $TunnelAddress = Get-Content "$env:TEMP\playit.log" -ErrorAction SilentlyContinue | Select-String -Pattern ".*\.playit\.gg:\d{1,5}|https://playit.gg/claim/.*" | ForEach-Object { $_.Matches.Value } | Select-Object -Last 1
          if (-not $TunnelAddress) { Write-Error "Error: No se pudo obtener la dirección del túnel."; Get-Content "$env:TEMP\playit_error.log"; exit 1 }
          Write-Host "================================================================="
          Write-Host "               ¡TÚNEL CREADO CON ÉXITO!"
          Write-Host "================================================================="
          Write-Host "   Dirección playit.gg: $TunnelAddress"
          Write-Host "   (Si es un enlace https, visítalo primero para reclamarlo)"
          Write-Host "   Usuario:             ${{ env:RDP_USER }}"
          Write-Host "   Contraseña:          ${{ env:RDP_PASSWORD }}"
          Write-Host "================================================================="
          Write-Host ""
          Write-Host "Este paso se mantendrá en ejecución para mantener la VPS activa."
          while ($true) { Start-Sleep -Seconds 60 }
