name: RDP Automático y Estable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: 1. Habilitar RDP, Usuario y Sonido
        run: |
          $Password = "P@ssw0rdFeloxPC2025!"
          net user Runner $Password /add /y
          net localgroup administrators Runner /add
          net localgroup "Remote Desktop Users" Runner /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389
          Set-Service -Name Audiosrv -StartupType Automatic
          Start-Service -Name Audiosrv
          echo "RDP_USER=Runner" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "RDP_PASSWORD=$Password" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: 2. Iniciar Túnel y Mantener Activo (Método Automático Estable)
        run: |
          # Descarga una versión fija de playit.gg.
          Invoke-WebRequest -Uri 'https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe' -OutFile "playit.exe"
          
          # Inicia playit en segundo plano.
          Start-Process -FilePath ".\playit.exe" -ArgumentList "" -NoNewWindow -RedirectStandardOutput "$env:TEMP\playit.log" -RedirectStandardError "$env:TEMP\playit_error.log"
          
          Write-Host "Esperando 30 segundos a que playit.gg se conecte..."
          Start-Sleep -Seconds 30
          
          # Intenta obtener la dirección del túnel o la URL de reclamación.
          $TunnelAddress = Get-Content "$env:TEMP\playit.log" -ErrorAction SilentlyContinue | Select-String -Pattern ".*\.playit\.gg:\d{1,5}|https://playit.gg/claim/.*" | ForEach-Object { $_.Matches.Value } | Select-Object -Last 1

          if (-not $TunnelAddress) {
            Write-Error "Error: No se pudo obtener la dirección del túnel. Revisa los logs."
            Get-Content "$env:TEMP\playit_error.log"
            exit 1
          }
          
          # --- El truco está aquí ---
          # Mostramos la información y luego mantenemos este paso vivo con un bucle.
          Write-Host "================================================================="
          Write-Host "               ¡TÚNEL CREADO CON ÉXITO!"
          Write-Host "================================================================="
          Write-Host "   Dirección playit.gg: $TunnelAddress"
          Write-Host "   (Si es un enlace https, visítalo primero para reclamarlo)"
          Write-Host "   Usuario:             ${{ env.RDP_USER }}"
          Write-Host "   Contraseña:          ${{ env.RDP_PASSWORD }}"
          Write-Host "================================================================="
          Write-Host ""
          Write-Host "Este paso se mantendrá en ejecución para mantener la VPS activa."
          Write-Host "Puedes cerrar la ventana de logs. Cancela el workflow en GitHub cuando termines."
          
          # Bucle "Keep-Alive": Mantiene el paso activo durante casi 6 horas.
          while ($true) {
            Start-Sleep -Seconds 60
          }
          
      # Ya no necesitamos los pasos de "Mostrar Credenciales" o "Mantener Activo"
      # porque todo se hace en el paso 2.
